name: angelkar.music
description: Rumblings about music for my future self
meta_description: ""

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://angelkar.music'
author:         'Angelos Karagkiozidis'
twitter:        'https://twitter.com/ang3lkar'
