name: Little Blue Fox
description: Rumblings about music for my future self
meta_description: ""

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: '/'
domain_name: 'https://little-blue-fox.com'
google_analytics: 'UA-36650511-2'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://little-blue-fox.com'
author:         'Angelos Karagkiozidis'
twitter:        'https://twitter.com/ang3lkar'
